version: '2'
services:
  web:
    image: nginx:latest
    volumes:
    - ${PWD}/doc/html/:/usr/share/nginx/html
    - ${PWD}/doc/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      benet:
  lb:
    image: haproxytech/haproxy-alpine:latest
    restart: always
    volumes:
    -  ${PWD}/doc/lb/:/usr/local/etc/haproxy:ro
    ports:
     - "80:80"
    networks:
      benet:
      default:

networks:
  benet:
    driver: bridge