- hosts: main
  become: true
  tasks:
    - name: Install PyMySQL
      apt:
        name: python3-mysqldb
        state: latest

    - name: Copy, mysql config files.
      ansible.builtin.copy:
        src: conf/mariadb/my.cnf
        dest: /etc/mysql
        owner: root
        group: root
        mode: '0644'  
    - name: Create DB
      become: true
      community.mysql.mysql_db:        
        name:
          - wiki
          - wordpress
          - glpi
          - phpbb
        state: present
    - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in wiki,wordpress,phpbb,glpi
      community.mysql.mysql_user:
        state: present
        name: user
        password: 123qwe
        host: '%'
        host_all: no
        host: "localhost"
        priv:
          'wiki.*': 'ALL,GRANT'
          'wordpress.*': 'ALL,GRANT'
          'phpbb.*': 'ALL,GRANT'
          'glpi.*': 'ALL,GRANT'    
    
    - name: Bootstrap a host without python2 installed
      become: true
      ansible.builtin.raw: systemctl restart mariadb 