Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_version = "20220901.0.0"
    
    config.vm.define "web" do |web|    
      web.vm.network "public_network", ip: "192.168.1.211", bridge: "en0: Wi-Fi (Wireless)"
      config.ssh.dsa_authentication
      config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
      config.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
    config.vm.define "web" do |web|    
        web.vm.network "public_network", ip: "192.168.1.212", bridge: "en0: Wi-Fi (Wireless)"
        config.ssh.dsa_authentication
        config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
        config.vm.provision "shell", inline: <<-SHELL
          cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
      end
    config.vm.define "web" do |web|    
    web.vm.network "public_network", ip: "192.168.1.213", bridge: "en0: Wi-Fi (Wireless)"
    config.ssh.dsa_authentication
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
    config.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
    end
end