version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
     - WORDPRESS_DB_HOST=db
     - WORDPRESS_DB_USER=${MYSQL_USER}
     - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
     - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: