- hosts: all
  tasks:
    - name: 'Update'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: 'Create Directory'
      file:
        path: /opt/www
        state: directory
        owner: www-data
        group: www-data
        mode: 0775


    - name: 'Instala pacotes do sistema operacional'
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - git