netplan_conf:
  network:
    ethernets:
      enp3s0:
        addresses:
        - 192.168.1.206/24
        gateway4: 192.168.1.1
        link: ens3
        nameservers:
          addresses:
          - 8.8.8.8
          - 8.8.4.4