# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.box = "gremid/debian-4.0r9-x64"
    # config.vm.box_version = "0.1.0"
    
    config.vm.define "core" do |core|    
      core.vm.network "public_network", ip: "192.168.1.213", bridge: "en0: Wi-Fi (Wireless)"
      config.ssh.dsa_authentication
      config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
      config.vm.provision "shell", inline: <<-SHELL
        cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
    