- hosts: main
  become: true
  tasks:

    - name: pwds
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout

    - name: Copy, default repositoryes config files.
      ansible.builtin.copy:
        src: conf/default.source.list
        dest: /etc/apt/source.list
        owner: root
        group: root
        mode: '0644'
  
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Lamp + Python - dependencias para wordpress
      ansible.builtin.apt:
        pkg:
          - apache2
          - mariadb-server
          - python3
          - php
          - libapache2-mod-php
          - php-mysql
          - unzip
    - name: Dependencias para Glpi 9.5, para >php-7.2.3
      ansible.builtin.apt:
        pkg:
          - php-curl
          - php-gd
          - php-intl
          - php-xml
          - php-common
          - php-xml
          - php-mbstring
    - name: Dependencias para Docker, via composer.
      ansible.builtin.apt:
        pkg:
          - docker.io