# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.box = "debian11"
  config.ssh.private_key_path="/Users/rodrigo.silva.cunha/Documents/WorkDir/OFF/iac/vagrant/credencials/private-key"
  config.vm.define "core" do |core|    
    core.vm.network "public_network", ip: "192.168.1.223", bridge: "en0: Wi-Fi (Wireless)"
    config.ssh.dsa_authentication
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/me.pub"    
    config.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
    config.vm.provision "file", source: "config/default.source.list", destination: "~/"
    config.vm.provision "shell", inline: <<-SHELL
      sudo cp default.source.list /etc/apt/sources.list.d/    
    SHELL
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update    
    SHELL
  end
end