- hosts: main
  become: true
  tasks:
    # - name: Corrigindo repositórios depecrated do debian.
    #   ansible.builtin.shell:
    #     cmd: rm  /etc/apt/source.list
    # - name: Inserindo um novo source.list
    #   ansible.builtin.copy:
    #     src: /Users/rodrigo.silva.cunha/Documents/WorkDir/OFF/iac/vagrant/zabbixb/config/vagrant/sources.list
    #     dest: /etc/apt/
    #     owner: root
    #     group: root
    #     mode: '0644'
  
  
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Lamp + Python - dependencias para wordpress
      ansible.builtin.apt:
        pkg:
          - apache2
          - mariadb-server
          - python3
          - php
          - libapache2-mod-php
          - php-mysql
          - unzip
    - name: Dependencias para Glpi
      ansible.builtin.apt:
        pkg:
          - php8.1-curl
          - php8.1-gd
          - php8.1-intl
          - php8.1-xml
          - php8.1-common
          - php-xml